// Generated by ResgenSwift.Color 2.2.0

import SwiftUI

extension Color {

    /// Color neutral50 is #f0f2f4 (light) or #f0f2f4 (dark)"
    package static var neutral50: Color {
        Color("neutral50", bundle: Bundle.module)
    }

    /// Color neutral100 is #dae1eb (light) or #dae1eb (dark)"
    package static var neutral100: Color {
        Color("neutral100", bundle: Bundle.module)
    }

    /// Color neutral200 is #9ca7b7 (light) or #9ca7b7 (dark)"
    package static var neutral200: Color {
        Color("neutral200", bundle: Bundle.module)
    }

    /// Color neutral300 is #7b8a9f (light) or #7b8a9f (dark)"
    package static var neutral300: Color {
        Color("neutral300", bundle: Bundle.module)
    }

    /// Color neutral400 is #5a6d87 (light) or #5a6d87 (dark)"
    package static var neutral400: Color {
        Color("neutral400", bundle: Bundle.module)
    }

    /// Color neutral500 is #353f4f (light) or #353f4f (dark)"
    package static var neutral500: Color {
        Color("neutral500", bundle: Bundle.module)
    }

    /// Color neutral600 is #2f3745 (light) or #2f3745 (dark)"
    package static var neutral600: Color {
        Color("neutral600", bundle: Bundle.module)
    }

    /// Color neutral700 is #292f3b (light) or #292f3b (dark)"
    package static var neutral700: Color {
        Color("neutral700", bundle: Bundle.module)
    }

    /// Color neutral800 is #232731 (light) or #232731 (dark)"
    package static var neutral800: Color {
        Color("neutral800", bundle: Bundle.module)
    }

    /// Color neutral900 is #1d1f27 (light) or #1d1f27 (dark)"
    package static var neutral900: Color {
        Color("neutral900", bundle: Bundle.module)
    }

    /// Color neutral950 is #0e111a (light) or #0e111a (dark)"
    package static var neutral950: Color {
        Color("neutral950", bundle: Bundle.module)
    }

    /// Color red50 is #fef2f2 (light) or #fef2f2 (dark)"
    package static var red50: Color {
        Color("red50", bundle: Bundle.module)
    }

    /// Color red100 is #fee2e2 (light) or #fee2e2 (dark)"
    package static var red100: Color {
        Color("red100", bundle: Bundle.module)
    }

    /// Color red200 is #fecaca (light) or #fecaca (dark)"
    package static var red200: Color {
        Color("red200", bundle: Bundle.module)
    }

    /// Color red300 is #fca5a5 (light) or #fca5a5 (dark)"
    package static var red300: Color {
        Color("red300", bundle: Bundle.module)
    }

    /// Color red400 is #f87171 (light) or #f87171 (dark)"
    package static var red400: Color {
        Color("red400", bundle: Bundle.module)
    }

    /// Color red500 is #ef4444 (light) or #ef4444 (dark)"
    package static var red500: Color {
        Color("red500", bundle: Bundle.module)
    }

    /// Color red600 is #dc2626 (light) or #dc2626 (dark)"
    package static var red600: Color {
        Color("red600", bundle: Bundle.module)
    }

    /// Color red700 is #b91c1c (light) or #b91c1c (dark)"
    package static var red700: Color {
        Color("red700", bundle: Bundle.module)
    }

    /// Color red800 is #991b1b (light) or #991b1b (dark)"
    package static var red800: Color {
        Color("red800", bundle: Bundle.module)
    }

    /// Color red900 is #7f1d1d (light) or #7f1d1d (dark)"
    package static var red900: Color {
        Color("red900", bundle: Bundle.module)
    }

    /// Color red950 is #450a0a (light) or #450a0a (dark)"
    package static var red950: Color {
        Color("red950", bundle: Bundle.module)
    }

    /// Color orange50 is #fff7ed (light) or #fff7ed (dark)"
    package static var orange50: Color {
        Color("orange50", bundle: Bundle.module)
    }

    /// Color orange100 is #ffedd5 (light) or #ffedd5 (dark)"
    package static var orange100: Color {
        Color("orange100", bundle: Bundle.module)
    }

    /// Color orange200 is #fed7aa (light) or #fed7aa (dark)"
    package static var orange200: Color {
        Color("orange200", bundle: Bundle.module)
    }

    /// Color orange300 is #fdba74 (light) or #fdba74 (dark)"
    package static var orange300: Color {
        Color("orange300", bundle: Bundle.module)
    }

    /// Color orange400 is #fb923c (light) or #fb923c (dark)"
    package static var orange400: Color {
        Color("orange400", bundle: Bundle.module)
    }

    /// Color orange500 is #f97316 (light) or #f97316 (dark)"
    package static var orange500: Color {
        Color("orange500", bundle: Bundle.module)
    }

    /// Color orange600 is #ea580c (light) or #ea580c (dark)"
    package static var orange600: Color {
        Color("orange600", bundle: Bundle.module)
    }

    /// Color orange700 is #c2410c (light) or #c2410c (dark)"
    package static var orange700: Color {
        Color("orange700", bundle: Bundle.module)
    }

    /// Color orange800 is #9a3412 (light) or #9a3412 (dark)"
    package static var orange800: Color {
        Color("orange800", bundle: Bundle.module)
    }

    /// Color orange900 is #7c2d12 (light) or #7c2d12 (dark)"
    package static var orange900: Color {
        Color("orange900", bundle: Bundle.module)
    }

    /// Color orange950 is #431407 (light) or #431407 (dark)"
    package static var orange950: Color {
        Color("orange950", bundle: Bundle.module)
    }

    /// Color green50 is #f0fdf4 (light) or #f0fdf4 (dark)"
    package static var green50: Color {
        Color("green50", bundle: Bundle.module)
    }

    /// Color green100 is #dcfce7 (light) or #dcfce7 (dark)"
    package static var green100: Color {
        Color("green100", bundle: Bundle.module)
    }

    /// Color green200 is #bbf7d0 (light) or #bbf7d0 (dark)"
    package static var green200: Color {
        Color("green200", bundle: Bundle.module)
    }

    /// Color green300 is #86efac (light) or #86efac (dark)"
    package static var green300: Color {
        Color("green300", bundle: Bundle.module)
    }

    /// Color green400 is #4ade80 (light) or #4ade80 (dark)"
    package static var green400: Color {
        Color("green400", bundle: Bundle.module)
    }

    /// Color green500 is #22c55e (light) or #22c55e (dark)"
    package static var green500: Color {
        Color("green500", bundle: Bundle.module)
    }

    /// Color green600 is #16a34a (light) or #16a34a (dark)"
    package static var green600: Color {
        Color("green600", bundle: Bundle.module)
    }

    /// Color green700 is #15803d (light) or #15803d (dark)"
    package static var green700: Color {
        Color("green700", bundle: Bundle.module)
    }

    /// Color green800 is #166534 (light) or #166534 (dark)"
    package static var green800: Color {
        Color("green800", bundle: Bundle.module)
    }

    /// Color green900 is #14532d (light) or #14532d (dark)"
    package static var green900: Color {
        Color("green900", bundle: Bundle.module)
    }

    /// Color green950 is #052e16 (light) or #052e16 (dark)"
    package static var green950: Color {
        Color("green950", bundle: Bundle.module)
    }

    /// Color light100 is #ffffff (light) or #ffffff (dark)"
    package static var light100: Color {
        Color("light100", bundle: Bundle.module)
    }

    /// Color light90 is #ffffffe5 (light) or #ffffffe5 (dark)"
    package static var light90: Color {
        Color("light90", bundle: Bundle.module)
    }

    /// Color light80 is #ffffffcc (light) or #ffffffcc (dark)"
    package static var light80: Color {
        Color("light80", bundle: Bundle.module)
    }

    /// Color light70 is #ffffffb2 (light) or #ffffffb2 (dark)"
    package static var light70: Color {
        Color("light70", bundle: Bundle.module)
    }

    /// Color light60 is #ffffff99 (light) or #ffffff99 (dark)"
    package static var light60: Color {
        Color("light60", bundle: Bundle.module)
    }

    /// Color light50 is #ffffff7f (light) or #ffffff7f (dark)"
    package static var light50: Color {
        Color("light50", bundle: Bundle.module)
    }

    /// Color light40 is #ffffff66 (light) or #ffffff66 (dark)"
    package static var light40: Color {
        Color("light40", bundle: Bundle.module)
    }

    /// Color light30 is #ffffff4c (light) or #ffffff4c (dark)"
    package static var light30: Color {
        Color("light30", bundle: Bundle.module)
    }

    /// Color light20 is #ffffff33 (light) or #ffffff33 (dark)"
    package static var light20: Color {
        Color("light20", bundle: Bundle.module)
    }

    /// Color light10 is #ffffff19 (light) or #ffffff19 (dark)"
    package static var light10: Color {
        Color("light10", bundle: Bundle.module)
    }

    /// Color light8 is #ffffff14 (light) or #ffffff14 (dark)"
    package static var light8: Color {
        Color("light8", bundle: Bundle.module)
    }

    /// Color light6 is #ffffff0f (light) or #ffffff0f (dark)"
    package static var light6: Color {
        Color("light6", bundle: Bundle.module)
    }

    /// Color light4 is #ffffff0a (light) or #ffffff0a (dark)"
    package static var light4: Color {
        Color("light4", bundle: Bundle.module)
    }

    /// Color light2 is #ffffff05 (light) or #ffffff05 (dark)"
    package static var light2: Color {
        Color("light2", bundle: Bundle.module)
    }

    /// Color light0 is #ffffff00 (light) or #ffffff00 (dark)"
    package static var light0: Color {
        Color("light0", bundle: Bundle.module)
    }

    /// Color dark100 is #09090b (light) or #09090b (dark)"
    package static var dark100: Color {
        Color("dark100", bundle: Bundle.module)
    }

    /// Color dark90 is #09090be5 (light) or #09090be5 (dark)"
    package static var dark90: Color {
        Color("dark90", bundle: Bundle.module)
    }

    /// Color dark80 is #09090bcc (light) or #09090bcc (dark)"
    package static var dark80: Color {
        Color("dark80", bundle: Bundle.module)
    }

    /// Color dark70 is #09090bb2 (light) or #09090bb2 (dark)"
    package static var dark70: Color {
        Color("dark70", bundle: Bundle.module)
    }

    /// Color dark60 is #09090b99 (light) or #09090b99 (dark)"
    package static var dark60: Color {
        Color("dark60", bundle: Bundle.module)
    }

    /// Color dark50 is #09090b7f (light) or #09090b7f (dark)"
    package static var dark50: Color {
        Color("dark50", bundle: Bundle.module)
    }

    /// Color dark40 is #09090b66 (light) or #09090b66 (dark)"
    package static var dark40: Color {
        Color("dark40", bundle: Bundle.module)
    }

    /// Color dark30 is #09090b4c (light) or #09090b4c (dark)"
    package static var dark30: Color {
        Color("dark30", bundle: Bundle.module)
    }

    /// Color dark20 is #09090b33 (light) or #09090b33 (dark)"
    package static var dark20: Color {
        Color("dark20", bundle: Bundle.module)
    }

    /// Color dark10 is #09090b19 (light) or #09090b19 (dark)"
    package static var dark10: Color {
        Color("dark10", bundle: Bundle.module)
    }

    /// Color dark8 is #09090b14 (light) or #09090b14 (dark)"
    package static var dark8: Color {
        Color("dark8", bundle: Bundle.module)
    }

    /// Color dark6 is #09090b0f (light) or #09090b0f (dark)"
    package static var dark6: Color {
        Color("dark6", bundle: Bundle.module)
    }

    /// Color dark4 is #09090b0a (light) or #09090b0a (dark)"
    package static var dark4: Color {
        Color("dark4", bundle: Bundle.module)
    }

    /// Color dark2 is #09090b05 (light) or #09090b05 (dark)"
    package static var dark2: Color {
        Color("dark2", bundle: Bundle.module)
    }

    /// Color dark0 is #09090b00 (light) or #09090b00 (dark)"
    package static var dark0: Color {
        Color("dark0", bundle: Bundle.module)
    }

    /// Color transparent is #00000000 (light) or #00000000 (dark)"
    package static var transparent: Color {
        Color("transparent", bundle: Bundle.module)
    }
    
    /// Color transparent is #4A70A9 (light) or #4A70A9 (dark)"
    package static var zzBlue: Color {
        Color("zzBlue", bundle: Bundle.module)
    }
    
    /// Color transparent is #8FABD4 (light) or #8FABD4 (dark)"
    package static var zzLightBlue: Color {
        Color("zzLightBlue", bundle: Bundle.module)
    }
    
    /// Color transparent is #2F4060 (light) or #2F4060 (dark)"
    package static var zzDarkBlue: Color {
        Color("zzDarkBlue", bundle: Bundle.module)
    }
    
    /// Color transparent is #EFECE3 (light) or #EFECE3 (dark)"
    package static var zzBeige: Color {
        Color("zzBeige", bundle: Bundle.module)
    }
}
