// Generated by ResgenSwift.Color 2.1.0

import UIKit

extension UIColor {

    /// Color neutral50 is #f0f2f4 (light) or #f0f2f4 (dark)"
    static var neutral50: UIColor {
        UIColor(named: "neutral50")!
    }

    /// Color neutral100 is #dae1eb (light) or #dae1eb (dark)"
    static var neutral100: UIColor {
        UIColor(named: "neutral100")!
    }

    /// Color neutral200 is #9ca7b7 (light) or #9ca7b7 (dark)"
    static var neutral200: UIColor {
        UIColor(named: "neutral200")!
    }

    /// Color neutral300 is #7b8a9f (light) or #7b8a9f (dark)"
    static var neutral300: UIColor {
        UIColor(named: "neutral300")!
    }

    /// Color neutral400 is #5a6d87 (light) or #5a6d87 (dark)"
    static var neutral400: UIColor {
        UIColor(named: "neutral400")!
    }

    /// Color neutral500 is #353f4f (light) or #353f4f (dark)"
    static var neutral500: UIColor {
        UIColor(named: "neutral500")!
    }

    /// Color neutral600 is #2f3745 (light) or #2f3745 (dark)"
    static var neutral600: UIColor {
        UIColor(named: "neutral600")!
    }

    /// Color neutral700 is #292f3b (light) or #292f3b (dark)"
    static var neutral700: UIColor {
        UIColor(named: "neutral700")!
    }

    /// Color neutral800 is #232731 (light) or #232731 (dark)"
    static var neutral800: UIColor {
        UIColor(named: "neutral800")!
    }

    /// Color neutral900 is #1d1f27 (light) or #1d1f27 (dark)"
    static var neutral900: UIColor {
        UIColor(named: "neutral900")!
    }

    /// Color neutral950 is #0e111a (light) or #0e111a (dark)"
    static var neutral950: UIColor {
        UIColor(named: "neutral950")!
    }

    /// Color red50 is #fef2f2 (light) or #fef2f2 (dark)"
    static var red50: UIColor {
        UIColor(named: "red50")!
    }

    /// Color red100 is #fee2e2 (light) or #fee2e2 (dark)"
    static var red100: UIColor {
        UIColor(named: "red100")!
    }

    /// Color red200 is #fecaca (light) or #fecaca (dark)"
    static var red200: UIColor {
        UIColor(named: "red200")!
    }

    /// Color red300 is #fca5a5 (light) or #fca5a5 (dark)"
    static var red300: UIColor {
        UIColor(named: "red300")!
    }

    /// Color red400 is #f87171 (light) or #f87171 (dark)"
    static var red400: UIColor {
        UIColor(named: "red400")!
    }

    /// Color red500 is #ef4444 (light) or #ef4444 (dark)"
    static var red500: UIColor {
        UIColor(named: "red500")!
    }

    /// Color red600 is #dc2626 (light) or #dc2626 (dark)"
    static var red600: UIColor {
        UIColor(named: "red600")!
    }

    /// Color red700 is #b91c1c (light) or #b91c1c (dark)"
    static var red700: UIColor {
        UIColor(named: "red700")!
    }

    /// Color red800 is #991b1b (light) or #991b1b (dark)"
    static var red800: UIColor {
        UIColor(named: "red800")!
    }

    /// Color red900 is #7f1d1d (light) or #7f1d1d (dark)"
    static var red900: UIColor {
        UIColor(named: "red900")!
    }

    /// Color red950 is #450a0a (light) or #450a0a (dark)"
    static var red950: UIColor {
        UIColor(named: "red950")!
    }

    /// Color orange50 is #fff7ed (light) or #fff7ed (dark)"
    static var orange50: UIColor {
        UIColor(named: "orange50")!
    }

    /// Color orange100 is #ffedd5 (light) or #ffedd5 (dark)"
    static var orange100: UIColor {
        UIColor(named: "orange100")!
    }

    /// Color orange200 is #fed7aa (light) or #fed7aa (dark)"
    static var orange200: UIColor {
        UIColor(named: "orange200")!
    }

    /// Color orange300 is #fdba74 (light) or #fdba74 (dark)"
    static var orange300: UIColor {
        UIColor(named: "orange300")!
    }

    /// Color orange400 is #fb923c (light) or #fb923c (dark)"
    static var orange400: UIColor {
        UIColor(named: "orange400")!
    }

    /// Color orange500 is #f97316 (light) or #f97316 (dark)"
    static var orange500: UIColor {
        UIColor(named: "orange500")!
    }

    /// Color orange600 is #ea580c (light) or #ea580c (dark)"
    static var orange600: UIColor {
        UIColor(named: "orange600")!
    }

    /// Color orange700 is #c2410c (light) or #c2410c (dark)"
    static var orange700: UIColor {
        UIColor(named: "orange700")!
    }

    /// Color orange800 is #9a3412 (light) or #9a3412 (dark)"
    static var orange800: UIColor {
        UIColor(named: "orange800")!
    }

    /// Color orange900 is #7c2d12 (light) or #7c2d12 (dark)"
    static var orange900: UIColor {
        UIColor(named: "orange900")!
    }

    /// Color orange950 is #431407 (light) or #431407 (dark)"
    static var orange950: UIColor {
        UIColor(named: "orange950")!
    }

    /// Color green50 is #f0fdf4 (light) or #f0fdf4 (dark)"
    static var green50: UIColor {
        UIColor(named: "green50")!
    }

    /// Color green100 is #dcfce7 (light) or #dcfce7 (dark)"
    static var green100: UIColor {
        UIColor(named: "green100")!
    }

    /// Color green200 is #bbf7d0 (light) or #bbf7d0 (dark)"
    static var green200: UIColor {
        UIColor(named: "green200")!
    }

    /// Color green300 is #86efac (light) or #86efac (dark)"
    static var green300: UIColor {
        UIColor(named: "green300")!
    }

    /// Color green400 is #4ade80 (light) or #4ade80 (dark)"
    static var green400: UIColor {
        UIColor(named: "green400")!
    }

    /// Color green500 is #22c55e (light) or #22c55e (dark)"
    static var green500: UIColor {
        UIColor(named: "green500")!
    }

    /// Color green600 is #16a34a (light) or #16a34a (dark)"
    static var green600: UIColor {
        UIColor(named: "green600")!
    }

    /// Color green700 is #15803d (light) or #15803d (dark)"
    static var green700: UIColor {
        UIColor(named: "green700")!
    }

    /// Color green800 is #166534 (light) or #166534 (dark)"
    static var green800: UIColor {
        UIColor(named: "green800")!
    }

    /// Color green900 is #14532d (light) or #14532d (dark)"
    static var green900: UIColor {
        UIColor(named: "green900")!
    }

    /// Color green950 is #052e16 (light) or #052e16 (dark)"
    static var green950: UIColor {
        UIColor(named: "green950")!
    }

    /// Color light100 is #ffffff (light) or #ffffff (dark)"
    static var light100: UIColor {
        UIColor(named: "light100")!
    }

    /// Color light90 is #ffffffe5 (light) or #ffffffe5 (dark)"
    static var light90: UIColor {
        UIColor(named: "light90")!
    }

    /// Color light80 is #ffffffcc (light) or #ffffffcc (dark)"
    static var light80: UIColor {
        UIColor(named: "light80")!
    }

    /// Color light70 is #ffffffb2 (light) or #ffffffb2 (dark)"
    static var light70: UIColor {
        UIColor(named: "light70")!
    }

    /// Color light60 is #ffffff99 (light) or #ffffff99 (dark)"
    static var light60: UIColor {
        UIColor(named: "light60")!
    }

    /// Color light50 is #ffffff7f (light) or #ffffff7f (dark)"
    static var light50: UIColor {
        UIColor(named: "light50")!
    }

    /// Color light40 is #ffffff66 (light) or #ffffff66 (dark)"
    static var light40: UIColor {
        UIColor(named: "light40")!
    }

    /// Color light30 is #ffffff4c (light) or #ffffff4c (dark)"
    static var light30: UIColor {
        UIColor(named: "light30")!
    }

    /// Color light20 is #ffffff33 (light) or #ffffff33 (dark)"
    static var light20: UIColor {
        UIColor(named: "light20")!
    }

    /// Color light10 is #ffffff19 (light) or #ffffff19 (dark)"
    static var light10: UIColor {
        UIColor(named: "light10")!
    }

    /// Color light8 is #ffffff14 (light) or #ffffff14 (dark)"
    static var light8: UIColor {
        UIColor(named: "light8")!
    }

    /// Color light6 is #ffffff0f (light) or #ffffff0f (dark)"
    static var light6: UIColor {
        UIColor(named: "light6")!
    }

    /// Color light4 is #ffffff0a (light) or #ffffff0a (dark)"
    static var light4: UIColor {
        UIColor(named: "light4")!
    }

    /// Color light2 is #ffffff05 (light) or #ffffff05 (dark)"
    static var light2: UIColor {
        UIColor(named: "light2")!
    }

    /// Color light0 is #ffffff00 (light) or #ffffff00 (dark)"
    static var light0: UIColor {
        UIColor(named: "light0")!
    }

    /// Color dark100 is #09090b (light) or #09090b (dark)"
    static var dark100: UIColor {
        UIColor(named: "dark100")!
    }

    /// Color dark90 is #09090be5 (light) or #09090be5 (dark)"
    static var dark90: UIColor {
        UIColor(named: "dark90")!
    }

    /// Color dark80 is #09090bcc (light) or #09090bcc (dark)"
    static var dark80: UIColor {
        UIColor(named: "dark80")!
    }

    /// Color dark70 is #09090bb2 (light) or #09090bb2 (dark)"
    static var dark70: UIColor {
        UIColor(named: "dark70")!
    }

    /// Color dark60 is #09090b99 (light) or #09090b99 (dark)"
    static var dark60: UIColor {
        UIColor(named: "dark60")!
    }

    /// Color dark50 is #09090b7f (light) or #09090b7f (dark)"
    static var dark50: UIColor {
        UIColor(named: "dark50")!
    }

    /// Color dark40 is #09090b66 (light) or #09090b66 (dark)"
    static var dark40: UIColor {
        UIColor(named: "dark40")!
    }

    /// Color dark30 is #09090b4c (light) or #09090b4c (dark)"
    static var dark30: UIColor {
        UIColor(named: "dark30")!
    }

    /// Color dark20 is #09090b33 (light) or #09090b33 (dark)"
    static var dark20: UIColor {
        UIColor(named: "dark20")!
    }

    /// Color dark10 is #09090b19 (light) or #09090b19 (dark)"
    static var dark10: UIColor {
        UIColor(named: "dark10")!
    }

    /// Color dark8 is #09090b14 (light) or #09090b14 (dark)"
    static var dark8: UIColor {
        UIColor(named: "dark8")!
    }

    /// Color dark6 is #09090b0f (light) or #09090b0f (dark)"
    static var dark6: UIColor {
        UIColor(named: "dark6")!
    }

    /// Color dark4 is #09090b0a (light) or #09090b0a (dark)"
    static var dark4: UIColor {
        UIColor(named: "dark4")!
    }

    /// Color dark2 is #09090b05 (light) or #09090b05 (dark)"
    static var dark2: UIColor {
        UIColor(named: "dark2")!
    }

    /// Color dark0 is #09090b00 (light) or #09090b00 (dark)"
    static var dark0: UIColor {
        UIColor(named: "dark0")!
    }

    /// Color transparent is #00000000 (light) or #00000000 (dark)"
    static var transparent: UIColor {
        UIColor(named: "transparent")!
    }
    
    /// Color transparent is #4A70A9 (light) or #4A70A9 (dark)"
    package static var zzBlue: UIColor {
        UIColor(named: "zzBlue")!
    }
    
    /// Color transparent is #8FABD4 (light) or #8FABD4 (dark)"
    package static var zzLightBlue: UIColor {
        UIColor(named: "zzLightBlue")!
    }
    
    /// Color transparent is #2F4060 (light) or #2F4060 (dark)"
    package static var zzDarkBlue: UIColor {
        UIColor(named: "zzDarkBlue")!
    }
    
    /// Color transparent is #EFECE3 (light) or #EFECE3 (dark)"
    package static var zzBeige: UIColor {
        UIColor(named: "zzBeige")!
    }
}
